version: "3"
services:
  jenkinsservice:
    build: ./jenkins-service
    ports: 
      - "50000:50000"
    networks:
      - mobilenet
    volumes:
      - jenkins_home:/var/jenkins_home

  nginxservice:
    build: ./nginx-service
    ports:
      - "80:80"
    networks:
      - mobilenet
    volumes:
      - ./nginx-service/conf.d:/etc/nginx/conf.d
      - ./nginx-service/html:/usr/share/nginx/html
      - nginx_apache2:/etc/apache2
    depends_on:
      - jenkinsservice

networks:
  mobilenet:

volumes:
  jenkins_home:
  nginx_apache2:
